import { PERMISSIONS } from './persmissions.constants';

export const ROLES = {
  CEO: [
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.VIEW_APPOINTMENT,
    PERMISSIONS.APPROVE_REQUEST,
    PERMISSIONS.REASSIGN_REQUEST,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_INTEGRITY,
    PERMISSIONS.CHECK_IN,
    PERMISSIONS.CHECK_OUT,
  ],
  FRONT_DESK: [PERMISSIONS.CREATE_APPOINTMENT, PERMISSIONS.VIEW_APPOINTMENT],
  SECRETARY: [PERMISSIONS.CHECK_IN, PERMISSIONS.VIEW_APPOINTMENT],
  SECURITY: [PERMISSIONS.CHECK_OUT],
};
